server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?createDatabaseIfNotExist=true
    username: root
    password: Wambui123
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true